EXEC NSP_tblMovie_Insert 'A Nightmare on Elm Street (Freddy Krueger Series)';
EXEC NSP_tblMovie_Insert 'Abbott and Costello Meet Frankenstein';
EXEC NSP_tblMovie_Insert 'Absentia';
EXEC NSP_tblMovie_Insert 'The Act of Killing';
EXEC NSP_tblMovie_Insert 'Adaptation';
EXEC NSP_tblMovie_Insert 'The Addams Family';
EXEC NSP_tblMovie_Insert 'The Adventures of Buckaroo Banzai';
EXEC NSP_tblMovie_Insert 'After Hours';
EXEC NSP_tblMovie_Insert 'After Life';
EXEC NSP_tblMovie_Insert 'Against the Wall';
EXEC NSP_tblMovie_Insert 'Wrath of God Aguirre';
EXEC NSP_tblMovie_Insert 'Akira';
EXEC NSP_tblMovie_Insert 'Aladdin';
EXEC NSP_tblMovie_Insert 'Alan Partridge Alpha Papa';
EXEC NSP_tblMovie_Insert 'Alice in Wonderland';
EXEC NSP_tblMovie_Insert 'Alien (Series)';
EXEC NSP_tblMovie_Insert 'Alita Battle Angel';
EXEC NSP_tblMovie_Insert 'All About Eve';
EXEC NSP_tblMovie_Insert 'All Cheerleaders Die';
EXEC NSP_tblMovie_Insert 'All the Boys Love Mandy Lane';
EXEC NSP_tblMovie_Insert 'All the Colors of the Dark';